### PR TITLE
Bump thread gem to 0.1.7

### LINKED ISSUE #112: Changes today in `thread` gem prevent sneakers `work` method from being called
Spent the past few hours troubleshooting processing failures within an app using Sneakers on two different systems. No error messages, the `work` methods in my worker were just never getting called. I had a lot of changes to the app so I worked off the assumption that I had broken it. When I exhausted all the changes, I started looking at dependencies.

`ruby-thread` (`thread` gem) was updated four hours ago. Locking my Gemfile to thread's 0.1.5 version fixed it immediately. Not sure if my config has anything to do with it, let me know if I can help troubleshoot at all.

(Updating the subject, "break sneakers" is such a crappy description.)

### PR DESCRIPTION
**Pull request by nownabe**
thread gem v0.1.7 has be released to fix meh/ruby-thread/issues/34 .
This release also resolves #112 .

### CODE REVIEW

**Comment by nownabe** [comment]
I'm sorry for my many commits...
This build failed, but builds seems to fail sometimes independently of commits.

**Comment by rud** [comment]
@nownabe sounds like cross-talk between tests again, state being leaked or setup not being done. The CI setup is still a fairly recent thing, so it makes sense there are still some lingering issues. Any help in that regard would be appreciated, I'm sure, if at all possible.

**Comment by rud** [comment]
@nownabe, the unstable tests should be fixed in #116, no worries.

**Comment by nownabe** [comment]
@rud Thank you!! Test passed!

**Comment by jondot** [comment]
Awesome guys :)

**Pull request merged**
