### PR TITLE
Make heartbeat user configurable

### PR DESCRIPTION
**Pull request by salimane**
Currently the logging heartbeat is hardcoded. This pr makes it possible to set it through the config file

### CODE REVIEW

**Comment by rud** [comment]
Good idea. As a constructive suggestion, maybe provide a default value in the config. A test would also go a long way towards making this trivial to merge. Thoughts?

**Comment by salimane** [comment]
@rud there is already a default in the config at https://github.com/jondot/sneakers/blob/master/lib/sneakers/configuration.rb#L25 . But you're right, I should be adding a test example.
Thanks

**Comment by jondot** [comment]
@salimane this would be the AMQP heartbeat, the workers heartbeat relate to server_engine. I think it would make sense to separate the two for cases where people put a 0.5s heartbeat on their AMQP connections (I've seen that happen) - what do you think?

**Comment by salimane** [comment]
@jondot you're right. I've added an additional ``amqp_heartbeat`` config default to 10s.
Thanks

**Comment by michaelklishin** [comment]
FTR, heartbeat values lower than 5 seconds are not recommended: you will get false positives on high latency networks. Hutch used heartbeat value of 1 initially, it was bumped significantly after several production user complaints.

10 seconds sounds like a good default to me.

**Comment by jondot** [comment]
@michaelklishin thanks! sounds good to me too

**Comment by jondot** [comment]
@salimane thanks!, merging in!
:+1:

**Pull request merged**
