### PR TITLE
use #with_channel rather than maintaining a persistent channel and exchange

### PR DESCRIPTION
**Pull request by veetow**
https://github.com/jondot/sneakers/issues/192

### CODE REVIEW

**Comment by rud** [comment]
Ow, looks like a lot of the tests didn't behave too well. The change itself looks good to me. Anyone else?

**Comment by michaelklishin** [comment]
Using `with_channel` isn't critically important. I don't really object to it either.

What worries me is how many tests use mocks. Bunny uses no mocks.

**Comment by veetow** [comment]
Previously the `Bunny::Session` instance was only used in `#ensure_connection!` which in most examples was mocked out of the execution path (`mock(p).ensure_connection! {}`).  So now the extra mocking of Bunny is required due to the usage of `@bunny.with_channel` in the `#publish` method.  We're unit testing Sneakers here, not Bunny, so IMO these mocks are required.

**Comment by jondot** [comment]
@veetow question - do you somehow pool/cache your publisher? I'm wondering if you are still happy with a cached publisher that uses a single persistent connection. One that closes/opens one per message sounds a bit strange, I'm not sure what's the effect of this on RabbitMQ...

**Comment by veetow** [comment]
@jondot, I was not keeping a persistent publisher because I assumed that configuring a persisted Bunny::Session was good enough.  I've made some improvements to my code since, but I still think that using `#with_channel` here is more flexible and fool proof.  There's really no advantage to a long-lived channel.

**Comment by jondot** [comment]
Thanks @veetow, I am still wondering if opening/closing the connection for high rate of publishing repeatedly is thrashing RMQ. @michaelklishin is there any such effect that you know of by a chance ?

**Comment by veetow** [comment]
You mean by opening and closing the channel (not the connection)? Nope, as channels are multiplexed across the single connection.  Via `Sneakers.configure` I am passing in an existing `Bunny::Session` so there is no connection tear-down/set-up.

**Comment by michaelklishin** [comment]
This goes against how most messaging protocols are supposed to be used, and AMQP 0-9-1 in particular. I understand what kind of improvement this offers but opening a new channel per message will severely drop throughput (as it is a network roundtrip before you can do anything, in fact, in this case it is two because the new channel instance won't have the exchange cached!).

**Pull request closed without merging**
