### PR TITLE
Chore/enable travis ci

### PR DESCRIPTION
**Pull request by rud**
Still waiting for the tests to complete the first builds, but so far it looks good. Once this is merged you can enable the project on https://travis-ci.org

### CODE REVIEW

**Comment by rud** [comment]
Discussed in #55.

**Comment by rud** [comment]
Well, the inter-test pollution in #55 seems easy to reproduce. Current test-status can be seen at https://travis-ci.org/rud/sneakers.

**Comment by rud** [comment]
Alright, all set here.

**Comment by rud** [comment]
Any thoughts on these changes?

**Comment by michaelklishin** [comment]
Looks very useful.

**Comment by jondot** [comment]
Hey guys. I'm back from getting married. Thanks!! Will start merging :)

**Comment by michaelklishin** [comment]
@jondot congrats!

**Comment by lennartkoopmann** [comment]
@jondot Nice! Congrats!! :)

**Comment by rud** [comment]
@jondot thank you for the merge, and congratulations on your marriage :)

**Comment by jondot** [comment]
Thanks for the best wishes and for your awesome contribution guys :)

**Pull request merged**
