### PR TITLE
Bump dependent gem bunny version to enable mri timeout fixes

### PR DESCRIPTION
**Pull request by salimane**
Allow the new features and bug fixes in the new bunny release  http://blog.rubyrabbitmq.info/blog/2015/06/14/bunny-2-dot-0-0-rc1-is-released/ . Specially the ruby Timeout class fix (new “interruptor” thread per operation)
Thanks
ping @jondot

### CODE REVIEW

**Comment by michaelklishin** [comment]
I don't think depending on a pre-release version is such a bright idea.

**Comment by salimane** [comment]
@michaelklishin you could see that I've specified bunny between 1.7.0  and 2.0.0 . And from the blog post Bunny 2.0 doesn’t have any breaking API changes from 1.7.0 .
Thanks

**Comment by michaelklishin** [comment]
Fair enough. Bunny 2.0 is around the corner, too.

**Comment by salimane** [comment]
@michaelklishin bunny 2 has been released. https://rubygems.org/gems/bunny/versions/2.0.0 
Thanks

**Comment by michaelklishin** [comment]
@salimane I know. I released it ;)

**Comment by salimane** [comment]
@michaelklishin yep it was just a head up for the pr :smile:

**Comment by michaelklishin** [comment]
@jondot this PR LGTM and I'd recommend using Bunny 2.0 to most folks.

**Comment by michaelklishin** [comment]
One thing to keep in mind: Bunny 2.0 **requires Ruby 2.0+**. This may or may not be an issue for Sneakers but must be mentioned.

**Comment by jondot** [comment]
Hey guys, thanks for the PR (just back from sick leave and vacation) so was AFK.
Merging in!
:+1: :+1:

**Pull request merged**
