### PR TITLE
Introduce middlewares

### PR DESCRIPTION
**Pull request by andrykonchin**
Related issue https://github.com/jondot/sneakers/pull/323

It allows to use custom hooks/middlewares while job is processed.
The interface is similar to Rails:

```ruby
Sneakers.middleware.use(<class>, arguments)
Sneakers.middleware.delete(<class>)
```

Rails documentation - https://guides.rubyonrails.org/rails_on_rack.html#configuring-middleware-stack

Middleware should have following interface:

```ruby
class Middleware
  def initialize(app, <arguments>)
    ...
  end

  def call(message, delivery_info, metadata, handler)
    ...
  end
end
```

`#call` method should
- call next middleware passed into `#initialize` as `app` argument
- pass `message`, `delivery_info`, `metadata`, `handler` as arguments and
- modify and return result value.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@gabrieljoelc what do you think about the general approach?

**Comment by gabrieljoelc** [comment]
@andrykonchin thanks for doing this. Looks pretty good. Can you create a sample middleware in the samples to see it's use?

**Comment by andrykonchin** [comment]
@gabrieljoelc Done

**Comment by gabrieljoelc** [comment]
@michaelklishin you good with this?

**Comment by dukex** [comment]
Nice job @andrykonchin!

**Comment by gabrieljoelc** [comment]
@michaelklishin have you had a chance to review this?

**Comment by michaelklishin** [comment]
I think this should be seriously considered after the next release (which is long overdue).

**Comment by alipio** [comment]
Well done @andrykonchin! 💯

**Comment by fbbergamo** [comment]
Nice job @andrykonchin 
@michaelklishin  Is there anything that may help to get this merged?

**Pull request merged**
